# Generated by Django 5.2.7 on 2025-10-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='model_used',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
